version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example

networks:
  default:
    driver: overlay
